### ISSUE TITLE
Screen shots

### ISSUE THREAD

**Issue by ajtruckle** [mludlum/MarkdownPreview#1]
Can you please show me some screen shots of what this plug-in looks like in MantisBT?

And, does it work with the 2.5.1 edition?

**Comment by mludlum** [comment]
![mardownplugin screenshot](https://user-images.githubusercontent.com/3731744/27519705-1e6e3fb6-59c7-11e7-8d86-52293d97d61e.png)

Wherever there is a textarea with class form-control, it will respond to a lost focus, send the text to the server to process the markdown and place the results in a div below the textarea.

Give me some time to install and test on 2.5.1.  I have 2.0.1 installed.

**Comment by ajtruckle** [comment]
Sounds great. Please let me know if it is OK for 2.5.1.

Thanks.

**Comment by mludlum** [comment]
It works in 2.5.1 in Edge and IE, but not in Chrome because there is an issue in 2.5.1 with Bootstrap 3 in Chrome.  This exception is raised in common.js which is a mantis file. 

Uncaught TypeError: $(...).bs_typeahead is not a function
    at HTMLDocument.<anonymous> (common.js:100)
    at i (jquery-2.2.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2)
    at Function.ready (jquery-2.2.4.min.js:2)
    at HTMLDocument.J (jquery-2.2.4.min.js:2)

**Comment by ajtruckle** [comment]
Thanks. So is that fixable?

Sent from my iPhone

On 27 Jun 2017, at 15:39, mludlum <notifications@github.com<mailto:notifications@github.com>> wrote:


It works in 2.5.1 in Edge and IE, but not in Chrome because there is an issue in 2.5.1 with Bootstrap 3 in Chrome. This exception is raised in common.js which is a mantis file.

Uncaught TypeError: $(...).bs_typeahead is not a function
at HTMLDocument. (common.js:100)
at i (jquery-2.2.4.min.js:2)
at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2)
at Function.ready (jquery-2.2.4.min.js:2)
at HTMLDocument.J (jquery-2.2.4.min.js:2)

**Comment by mludlum** [comment]
I would imagine, but that is a core Mantis issue.  I have not touched that code.  It looks like you have developed a plugin that is a MarkDown Editor.  I installed it but couldn't get it to work.  It it browser security issues?

**Comment by ajtruckle** [comment]
No no, I have not developed anything. 😀

Someone else made a plug in for a markdown toolbar which has a preview feature but his had issues too so I stopped using it.

Since my programs a used world wide I need whatever plugin I use to operate in all the browsers etc. Can you raise your issue with mantis about your plug in?

The other guy doesn't seem to have done anything on his plugin in four months or so.

Andrew

Sent from my iPhone

On 27 Jun 2017, at 16:39, mludlum <notifications@github.com<mailto:notifications@github.com>> wrote:


I would imagine, but that is a core Mantis issue. I have not touched that code. It looks like you have developed a plugin that is a MarkDown Editor. I installed it but couldn't get it to work. It it browser security issues?

**Comment by mludlum** [comment]
Ooops!  Turns out it was a javascript caching issue.  I noticed the mantisbt.org site didn't have the problem.  Shift-F5 in Chrome forced reloading of new scripts.

So, it works fine in 2.5.1.

**Comment by ajtruckle** [comment]
I am a little confused.


I added your plugin.


Installed it.


Now I go to an existing topic and in the Add Note area I type some text.


I do not see a preview of any kind.


I am using Edge.


________________________________

**Comment by ajtruckle** [comment]
Got it to work. I forgot to add the pages sub folder.

So, when I type the text and then click into another text box the preview updates.

My only initial thoughts about adding notes to existing topics. I use this feature a lot and since I can't click into another edit box I can't see a preview for notes.

**Comment by mludlum** [comment]
Since I'm using ajax to  hit the server and translate, I'd rather not update constantly.  I could use a timer and update about every 5 seconds.  Whatya think?  Alternative would be a refresh button or a magic keystroke neither of which I"m crazy about.

**Comment by ajtruckle** [comment]
A button would be handy way. Makes the user aware that there *is* a preview pane below. I don't mind. If you prefer 5 sec timer. I am happy with your instincts with this.


And the "Add notes" ?


Andy


________________________________

**Comment by mludlum** [comment]
Added a 5 second timer to code in pages/mpreview.php

**Comment by ajtruckle** [comment]
Thanks. :)
